import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import {
  fetchLocalVariables,
  resolveVariableValue,
  colorToHex,
  cssName,
  type FigmaColor,
  type FigmaLocalVariablesResponse,
} from "./figma.ts";

const DEFAULT_FILE_KEY = "xWedurFoYbsD1iw9WW9wii"; // Figma "Chores" file

function declarations(entries: [string, string][]): string {
  return entries.map(([name, value]) => `  --${name}: ${value};`).join("\n");
}

/**
 * Reduces raw Figma variables/collections down to the color (light/dark) and
 * spacing maps that buildCss/buildTailwindTheme consume.
 */
export function extractTokens(meta: FigmaLocalVariablesResponse["meta"]): {
  colors: Record<string, { light: string; dark: string }>;
  spacing: Record<string, number>;
} {
  const { variables, variableCollections } = meta;
  const colors: Record<string, { light: string; dark: string }> = {};
  const spacing: Record<string, number> = {};

  for (const variable of Object.values(variables)) {
    const name = cssName(variable.name);

    if (variable.resolvedType === "COLOR") {
      const light = resolveVariableValue(variable, "Light", variables, variableCollections);
      const dark = resolveVariableValue(variable, "Dark", variables, variableCollections);
      colors[name] = {
        light: colorToHex(light as FigmaColor),
        dark: colorToHex(dark as FigmaColor),
      };
    } else if (variable.resolvedType === "FLOAT" && variable.name.startsWith("spacing/")) {
      const collection = variableCollections[variable.variableCollectionId];
      const value = variable.valuesByMode[collection.defaultModeId];
      spacing[name] = value as number;
    }
  }

  return { colors, spacing };
}

export function buildCss(
  fileKey: string,
  colors: Record<string, { light: string; dark: string }>,
  spacing: Record<string, number>,
): string {
  const lightColors = Object.entries(colors).map(
    ([name, { light }]): [string, string] => [name, light],
  );
  const darkColors = Object.entries(colors).map(
    ([name, { dark }]): [string, string] => [name, dark],
  );
  const spacingVars = Object.entries(spacing).map(
    ([name, value]): [string, string] => [name, `${value}px`],
  );

  return `/**
 * Generated by packages/tokens/src/build.ts — do not edit by hand.
 * Pulled live from Figma file variables (https://www.figma.com/design/${fileKey}) on every build.
 */

:root {
${declarations(lightColors)}

${declarations(spacingVars)}
}

@media (prefers-color-scheme: dark) {
  :root {
${declarations(darkColors)}
  }
}

:root[data-theme="dark"] {
${declarations(darkColors)}
}

:root[data-theme="light"] {
${declarations(lightColors)}
}
`;
}

export function buildTailwindTheme(colorNames: string[], spacingNames: string[]): string {
  const themeVars = [...colorNames, ...spacingNames].map(
    (name) => `  --${name}: var(--${name});`,
  );

  return `/**
 * Generated by packages/tokens/src/build.ts — do not edit by hand.
 * Registers the @chores/tokens custom properties as Tailwind CSS v4 theme
 * variables, so utilities (e.g. "bg-text-primary", "p-small") are generated
 * from them. Uses "@theme inline" rather than literal values so the
 * light/dark and [data-theme] switching in tokens.css keeps working.
 */

@import "./tokens.css";

@theme inline {
${themeVars.join("\n")}
}
`;
}

export async function main() {
  const fileKey = process.env.FIGMA_FILE_KEY ?? DEFAULT_FILE_KEY;
  const token = process.env.FIGMA_API_TOKEN;

  if (!token) {
    throw new Error(
      "FIGMA_API_TOKEN is not set. Create a personal access token with the " +
        "file_variables:read scope (requires an Enterprise-org account) and " +
        "set it in your environment before running this build.",
    );
  }

  const { meta } = await fetchLocalVariables(fileKey, token);
  const { colors, spacing } = extractTokens(meta);

  const outDir = fileURLToPath(new URL("../dist", import.meta.url));
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, "tokens.css"), buildCss(fileKey, colors, spacing));
  await writeFile(
    join(outDir, "tailwind.css"),
    buildTailwindTheme(Object.keys(colors), Object.keys(spacing)),
  );
  console.log(
    `Wrote packages/tokens/dist/tokens.css and dist/tailwind.css (${Object.keys(colors).length} color tokens, ${Object.keys(spacing).length} spacing tokens)`,
  );
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((err: unknown) => {
    console.error(err instanceof Error ? err.message : err);
    process.exitCode = 1;
  });
}
