-- SB-23: member profiles, parent/kid roles, member ids, PINs, and invites.
-- Generated by drizzle-kit, then reordered by hand so existing rows survive:
-- the role enum keeps its data (member -> kid), member rows get ids and
-- display names before the constraints go on, and chores.assigned_to (a user
-- id) is copied to assigned_member_id (a member id) before it's dropped.

-- household_role: owner | member  ->  owner | parent | kid.
-- Recreated rather than ALTER TYPE ... ADD VALUE, because a value added that
-- way can't be used in the same transaction, and drizzle-kit runs every
-- pending migration in one. Existing `member` rows become `kid` (the least
-- privileged role; an owner can promote parents). See schema/household-role.ts
-- for why this is one enum and not an is_parent flag.
ALTER TABLE "household_members" ALTER COLUMN "role" DROP DEFAULT;--> statement-breakpoint
ALTER TYPE "public"."household_role" RENAME TO "household_role_old";--> statement-breakpoint
CREATE TYPE "public"."household_role" AS ENUM('owner', 'parent', 'kid');--> statement-breakpoint
ALTER TABLE "household_members" ALTER COLUMN "role" SET DATA TYPE "public"."household_role"
	USING (CASE WHEN "role"::text = 'owner' THEN 'owner' ELSE 'kid' END)::"public"."household_role";--> statement-breakpoint
ALTER TABLE "household_members" ALTER COLUMN "role" SET DEFAULT 'kid';--> statement-breakpoint
DROP TYPE "public"."household_role_old";--> statement-breakpoint

-- household_members: a surrogate id, so managed kids (no auth user) can be
-- members. user_id becomes nullable and unique per household when present.
ALTER TABLE "household_members" ADD COLUMN "id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
ALTER TABLE "household_members" DROP CONSTRAINT "household_members_household_id_user_id_pk";--> statement-breakpoint
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "household_members" ALTER COLUMN "user_id" DROP NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "household_members_household_id_user_id_key" ON "household_members" USING btree ("household_id","user_id") WHERE "household_members"."user_id" is not null;--> statement-breakpoint

-- Profile fields. Existing members get their auth user's name as a display name.
ALTER TABLE "household_members" ADD COLUMN "display_name" text;--> statement-breakpoint
UPDATE "household_members" m
	SET "display_name" = coalesce(left(nullif(btrim(u."name"), ''), 50), 'Member')
	FROM "neon_auth"."user" u
	WHERE u."id" = m."user_id";--> statement-breakpoint
UPDATE "household_members" SET "display_name" = 'Member' WHERE "display_name" IS NULL;--> statement-breakpoint
ALTER TABLE "household_members" ALTER COLUMN "display_name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "household_members" ADD COLUMN "avatar_color" text;--> statement-breakpoint
ALTER TABLE "household_members" ADD COLUMN "avatar_initial" text;--> statement-breakpoint
ALTER TABLE "household_members" ADD COLUMN "birth_year" smallint;--> statement-breakpoint
ALTER TABLE "household_members" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_display_name_check" CHECK (char_length(btrim("household_members"."display_name")) between 1 and 50);--> statement-breakpoint
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_avatar_color_check" CHECK ("household_members"."avatar_color" is null or char_length("household_members"."avatar_color") between 1 and 32);--> statement-breakpoint
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_avatar_initial_check" CHECK ("household_members"."avatar_initial" is null or char_length("household_members"."avatar_initial") between 1 and 2);--> statement-breakpoint
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_birth_year_check" CHECK ("household_members"."birth_year" is null or "household_members"."birth_year" between 1900 and 2200);--> statement-breakpoint
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_managed_is_kid_check" CHECK ("household_members"."user_id" is not null or "household_members"."role" = 'kid');--> statement-breakpoint

-- chores.assigned_to (neon_auth user id) -> chores.assigned_member_id
-- (household_members id). Renamed so code still passing user ids fails to
-- compile instead of silently writing the wrong kind of id.
ALTER TABLE "chores" ADD COLUMN "assigned_member_id" uuid;--> statement-breakpoint
UPDATE "chores" c
	SET "assigned_member_id" = m."id"
	FROM "household_members" m
	WHERE m."household_id" = c."household_id" AND m."user_id" = c."assigned_to";--> statement-breakpoint
ALTER TABLE "chores" ADD CONSTRAINT "chores_assigned_member_id_household_members_id_fk" FOREIGN KEY ("assigned_member_id") REFERENCES "public"."household_members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chores_assigned_member_id_idx" ON "chores" USING btree ("assigned_member_id");--> statement-breakpoint
-- The old policies refer to assigned_to, so replace them before dropping it.
-- Chores are now parent-only to write.
ALTER POLICY "chores_insert" ON "chores" TO authenticated_backend WITH CHECK (app.is_household_parent("chores"."household_id")
				and "chores"."created_by" = (select app.current_user_id())
				and ("chores"."assigned_member_id" is null or app.is_member_id_in("chores"."household_id", "chores"."assigned_member_id")));--> statement-breakpoint
ALTER POLICY "chores_update" ON "chores" TO authenticated_backend USING (app.is_household_parent("chores"."household_id")) WITH CHECK (app.is_household_parent("chores"."household_id")
				and ("chores"."assigned_member_id" is null or app.is_member_id_in("chores"."household_id", "chores"."assigned_member_id")));--> statement-breakpoint
ALTER POLICY "chores_delete" ON "chores" TO authenticated_backend USING (app.is_household_parent("chores"."household_id"));--> statement-breakpoint
DROP INDEX "chores_assigned_to_idx";--> statement-breakpoint
ALTER TABLE "chores" DROP CONSTRAINT "chores_assigned_to_user_id_fk";--> statement-breakpoint
ALTER TABLE "chores" DROP COLUMN "assigned_to";--> statement-breakpoint

-- household_members policies: owners manage everyone, parents manage kids.
ALTER POLICY "household_members_insert" ON "household_members" TO authenticated_backend WITH CHECK (app.is_household_owner("household_members"."household_id")
				or (app.is_household_parent("household_members"."household_id") and "household_members"."role" = 'kid' and "household_members"."user_id" is null));--> statement-breakpoint
ALTER POLICY "household_members_update" ON "household_members" TO authenticated_backend USING (app.is_household_owner("household_members"."household_id")
				or (app.is_household_parent("household_members"."household_id") and ("household_members"."role" = 'kid' or "household_members"."user_id" = (select app.current_user_id())))) WITH CHECK (app.is_household_owner("household_members"."household_id")
				or (app.is_household_parent("household_members"."household_id") and ("household_members"."role" = 'kid' or ("household_members"."user_id" = (select app.current_user_id()) and "household_members"."role" = 'parent'))));--> statement-breakpoint
ALTER POLICY "household_members_delete" ON "household_members" TO authenticated_backend USING (app.is_household_owner("household_members"."household_id")
				or (app.is_household_parent("household_members"."household_id") and "household_members"."role" = 'kid')
				or "household_members"."user_id" = (select app.current_user_id()));--> statement-breakpoint

-- Parent PINs for the managed-kid profile lock (SB-51).
CREATE TABLE "household_member_pins" (
	"member_id" uuid PRIMARY KEY NOT NULL,
	"pin_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "household_member_pins" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "household_member_pins" ADD CONSTRAINT "household_member_pins_member_id_household_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."household_members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "household_member_pins_select" ON "household_member_pins" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_own_member("household_member_pins"."member_id"));--> statement-breakpoint
CREATE POLICY "household_member_pins_insert" ON "household_member_pins" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_own_parent_member("household_member_pins"."member_id"));--> statement-breakpoint
CREATE POLICY "household_member_pins_update" ON "household_member_pins" AS PERMISSIVE FOR UPDATE TO "authenticated_backend" USING (app.is_own_member("household_member_pins"."member_id")) WITH CHECK (app.is_own_parent_member("household_member_pins"."member_id"));--> statement-breakpoint
CREATE POLICY "household_member_pins_delete" ON "household_member_pins" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_own_member("household_member_pins"."member_id"));--> statement-breakpoint

-- Email invitations.
CREATE TABLE "household_invites" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"email" text NOT NULL,
	"role" "household_role" DEFAULT 'kid' NOT NULL,
	"display_name" text,
	"token_hash" text NOT NULL,
	"invited_by" uuid DEFAULT app.current_user_id(),
	"expires_at" timestamp with time zone DEFAULT now() + interval '7 days' NOT NULL,
	"accepted_at" timestamp with time zone,
	"accepted_member_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "household_invites_role_check" CHECK ("household_invites"."role" <> 'owner'),
	CONSTRAINT "household_invites_email_check" CHECK ("household_invites"."email" ~ '^[^@\s]+@[^@\s]+$'),
	CONSTRAINT "household_invites_token_hash_check" CHECK ("household_invites"."token_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "household_invites_display_name_check" CHECK ("household_invites"."display_name" is null or char_length(btrim("household_invites"."display_name")) between 1 and 50)
);
--> statement-breakpoint
ALTER TABLE "household_invites" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "household_invites" ADD CONSTRAINT "household_invites_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "household_invites" ADD CONSTRAINT "household_invites_invited_by_user_id_fk" FOREIGN KEY ("invited_by") REFERENCES "neon_auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "household_invites" ADD CONSTRAINT "household_invites_accepted_member_id_household_members_id_fk" FOREIGN KEY ("accepted_member_id") REFERENCES "public"."household_members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "household_invites_token_hash_key" ON "household_invites" USING btree ("token_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "household_invites_household_id_email_key" ON "household_invites" USING btree ("household_id",lower("email")) WHERE "household_invites"."accepted_at" is null;--> statement-breakpoint
CREATE INDEX "household_invites_household_id_idx" ON "household_invites" USING btree ("household_id");--> statement-breakpoint
CREATE POLICY "household_invites_select" ON "household_invites" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_parent("household_invites"."household_id"));--> statement-breakpoint
CREATE POLICY "household_invites_insert" ON "household_invites" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK ("household_invites"."invited_by" = (select app.current_user_id())
				and "household_invites"."accepted_at" is null
				and "household_invites"."accepted_member_id" is null
				and (app.is_household_owner("household_invites"."household_id")
					or (app.is_household_parent("household_invites"."household_id") and "household_invites"."role" = 'kid')));--> statement-breakpoint
CREATE POLICY "household_invites_delete" ON "household_invites" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_household_owner("household_invites"."household_id")
				or (app.is_household_parent("household_invites"."household_id") and "household_invites"."role" = 'kid'));
