-- SB-24: chore types, points, frequency and due time; chore stages; and
-- per-period chore instances with stage progress. See "Recurrence" in
-- ../README.md for why each period is its own chore_instances row.
-- Generated by drizzle-kit; hand edits: this header, the chores unique
-- constraint moved before the FKs that need it, and the grants at the end.
-- Existing chores become personal, daily, 10-point chores.

CREATE TYPE "public"."chore_frequency" AS ENUM('daily', 'weekly', 'weekends');--> statement-breakpoint
CREATE TYPE "public"."chore_type" AS ENUM('personal', 'rotation');--> statement-breakpoint
CREATE TABLE "chore_instances" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"chore_id" uuid NOT NULL,
	"period_start" date NOT NULL,
	"assigned_member_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chore_instances_chore_id_period_start_key" UNIQUE("chore_id","period_start"),
	CONSTRAINT "chore_instances_id_chore_id_key" UNIQUE("id","chore_id")
);
--> statement-breakpoint
ALTER TABLE "chore_instances" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "chore_stage_progress" (
	"instance_id" uuid NOT NULL,
	"stage_id" uuid NOT NULL,
	"chore_id" uuid NOT NULL,
	"household_id" uuid NOT NULL,
	"completed_by_member_id" uuid,
	"completed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chore_stage_progress_pkey" PRIMARY KEY("instance_id","stage_id")
);
--> statement-breakpoint
ALTER TABLE "chore_stage_progress" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "chore_stages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"chore_id" uuid NOT NULL,
	"position" smallint NOT NULL,
	"title" text NOT NULL,
	"hint" text,
	"points" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chore_stages_chore_id_position_key" UNIQUE("chore_id","position"),
	CONSTRAINT "chore_stages_id_chore_id_key" UNIQUE("id","chore_id"),
	CONSTRAINT "chore_stages_position_check" CHECK ("chore_stages"."position" >= 1),
	CONSTRAINT "chore_stages_title_check" CHECK (char_length(btrim("chore_stages"."title")) between 1 and 100),
	CONSTRAINT "chore_stages_hint_check" CHECK ("chore_stages"."hint" is null or char_length("chore_stages"."hint") <= 500),
	CONSTRAINT "chore_stages_points_check" CHECK ("chore_stages"."points" >= 0)
);
--> statement-breakpoint
ALTER TABLE "chore_stages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chores" ADD COLUMN "type" "chore_type" DEFAULT 'personal' NOT NULL;--> statement-breakpoint
ALTER TABLE "chores" ADD COLUMN "points" integer DEFAULT 10 NOT NULL;--> statement-breakpoint
ALTER TABLE "chores" ADD COLUMN "frequency" "chore_frequency" DEFAULT 'daily' NOT NULL;--> statement-breakpoint
ALTER TABLE "chores" ADD COLUMN "due_time" time;--> statement-breakpoint
ALTER TABLE "chores" ADD COLUMN "due_label" text;--> statement-breakpoint
-- Hand-moved up from where drizzle-kit put it: the composite FKs below
-- reference chores(id, household_id), which needs this constraint first.
ALTER TABLE "chores" ADD CONSTRAINT "chores_id_household_id_key" UNIQUE("id","household_id");--> statement-breakpoint
ALTER TABLE "chore_instances" ADD CONSTRAINT "chore_instances_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_instances" ADD CONSTRAINT "chore_instances_assigned_member_id_household_members_id_fk" FOREIGN KEY ("assigned_member_id") REFERENCES "public"."household_members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_instances" ADD CONSTRAINT "chore_instances_chore_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chores"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_stage_progress" ADD CONSTRAINT "chore_stage_progress_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_stage_progress" ADD CONSTRAINT "chore_stage_progress_completed_by_member_id_household_members_id_fk" FOREIGN KEY ("completed_by_member_id") REFERENCES "public"."household_members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_stage_progress" ADD CONSTRAINT "chore_stage_progress_instance_fk" FOREIGN KEY ("instance_id","chore_id") REFERENCES "public"."chore_instances"("id","chore_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_stage_progress" ADD CONSTRAINT "chore_stage_progress_stage_fk" FOREIGN KEY ("stage_id","chore_id") REFERENCES "public"."chore_stages"("id","chore_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_stage_progress" ADD CONSTRAINT "chore_stage_progress_chore_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chores"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_stages" ADD CONSTRAINT "chore_stages_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_stages" ADD CONSTRAINT "chore_stages_chore_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chores"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chore_instances_household_id_period_start_idx" ON "chore_instances" USING btree ("household_id","period_start");--> statement-breakpoint
CREATE INDEX "chore_instances_assigned_member_id_idx" ON "chore_instances" USING btree ("assigned_member_id");--> statement-breakpoint
CREATE INDEX "chore_stage_progress_stage_id_idx" ON "chore_stage_progress" USING btree ("stage_id");--> statement-breakpoint
CREATE INDEX "chore_stage_progress_household_id_idx" ON "chore_stage_progress" USING btree ("household_id");--> statement-breakpoint
CREATE INDEX "chore_stages_household_id_idx" ON "chore_stages" USING btree ("household_id");--> statement-breakpoint
ALTER TABLE "chores" ADD CONSTRAINT "chores_points_check" CHECK ("chores"."points" >= 0);--> statement-breakpoint
ALTER TABLE "chores" ADD CONSTRAINT "chores_due_label_check" CHECK ("chores"."due_label" is null or char_length(btrim("chores"."due_label")) between 1 and 40);--> statement-breakpoint
CREATE POLICY "chore_instances_select" ON "chore_instances" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_instances"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_instances_insert" ON "chore_instances" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_member("chore_instances"."household_id")
				and ("chore_instances"."assigned_member_id" is null or app.is_member_id_in("chore_instances"."household_id", "chore_instances"."assigned_member_id")));--> statement-breakpoint
CREATE POLICY "chore_instances_update" ON "chore_instances" AS PERMISSIVE FOR UPDATE TO "authenticated_backend" USING (app.is_household_parent("chore_instances"."household_id")) WITH CHECK (app.is_household_parent("chore_instances"."household_id")
				and ("chore_instances"."assigned_member_id" is null or app.is_member_id_in("chore_instances"."household_id", "chore_instances"."assigned_member_id")));--> statement-breakpoint
CREATE POLICY "chore_instances_delete" ON "chore_instances" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_household_parent("chore_instances"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_stage_progress_select" ON "chore_stage_progress" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_stage_progress"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_stage_progress_insert" ON "chore_stage_progress" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_member("chore_stage_progress"."household_id")
				and app.is_member_id_in("chore_stage_progress"."household_id", "chore_stage_progress"."completed_by_member_id")
				and (app.is_household_parent("chore_stage_progress"."household_id") or app.can_act_as_member("chore_stage_progress"."completed_by_member_id")));--> statement-breakpoint
CREATE POLICY "chore_stage_progress_delete" ON "chore_stage_progress" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_household_parent("chore_stage_progress"."household_id")
				or app.can_act_as_member("chore_stage_progress"."completed_by_member_id"));--> statement-breakpoint
CREATE POLICY "chore_stages_select" ON "chore_stages" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_stages"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_stages_insert" ON "chore_stages" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_parent("chore_stages"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_stages_update" ON "chore_stages" AS PERMISSIVE FOR UPDATE TO "authenticated_backend" USING (app.is_household_parent("chore_stages"."household_id")) WITH CHECK (app.is_household_parent("chore_stages"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_stages_delete" ON "chore_stages" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_household_parent("chore_stages"."household_id"));--> statement-breakpoint

-- The default privileges from 0002 already cover these new tables; this keeps
-- the grants explicit (as 0005 does). RLS still decides which rows.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE chore_stages, chore_instances, chore_stage_progress TO authenticated_backend;
