-- SB-25: rotation loops. chore_rotations (one per rotation chore: scope,
-- label, current turn, done last) and chore_rotation_members (turn order and
-- eligibility). The turn-advance function, its triggers, and the "at least 2
-- eligible members" check are in 0009.
-- Generated by drizzle-kit; hand edits: this header, the household_members
-- unique constraint moved before the composite FK that needs it, the
-- position unique and current-member FK made DEFERRABLE INITIALLY DEFERRED
-- (reorders can swap positions; the rotation row is inserted before its
-- members), and the grants at the end.

CREATE TYPE "public"."rotation_scope" AS ENUM('whole_household', 'eligible_subset');--> statement-breakpoint
CREATE TABLE "chore_rotation_members" (
	"chore_id" uuid NOT NULL,
	"household_id" uuid NOT NULL,
	"member_id" uuid NOT NULL,
	"position" smallint NOT NULL,
	"eligible" boolean DEFAULT true NOT NULL,
	"exclusion_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chore_rotation_members_pkey" PRIMARY KEY("chore_id","member_id"),
	CONSTRAINT "chore_rotation_members_chore_id_position_key" UNIQUE("chore_id","position") DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT "chore_rotation_members_position_check" CHECK ("chore_rotation_members"."position" >= 1),
	CONSTRAINT "chore_rotation_members_exclusion_reason_check" CHECK (("chore_rotation_members"."eligible" and "chore_rotation_members"."exclusion_reason" is null)
				or (not "chore_rotation_members"."eligible" and char_length(btrim("chore_rotation_members"."exclusion_reason")) between 1 and 200))
);
--> statement-breakpoint
ALTER TABLE "chore_rotation_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "chore_rotations" (
	"chore_id" uuid PRIMARY KEY NOT NULL,
	"household_id" uuid NOT NULL,
	"scope" "rotation_scope" DEFAULT 'whole_household' NOT NULL,
	"scope_label" text,
	"current_member_id" uuid,
	"turn_started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_completed_member_id" uuid,
	"last_completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chore_rotations_chore_id_household_id_key" UNIQUE("chore_id","household_id"),
	CONSTRAINT "chore_rotations_scope_label_check" CHECK ("chore_rotations"."scope_label" is null or char_length(btrim("chore_rotations"."scope_label")) between 1 and 40)
);
--> statement-breakpoint
ALTER TABLE "chore_rotations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
-- Hand-moved up from where drizzle-kit put it: chore_rotation_members_member_fk
-- references household_members(id, household_id), which needs this first.
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_id_household_id_key" UNIQUE("id","household_id");--> statement-breakpoint
ALTER TABLE "chore_rotation_members" ADD CONSTRAINT "chore_rotation_members_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_rotation_members" ADD CONSTRAINT "chore_rotation_members_rotation_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chore_rotations"("chore_id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_rotation_members" ADD CONSTRAINT "chore_rotation_members_member_fk" FOREIGN KEY ("member_id","household_id") REFERENCES "public"."household_members"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_rotations" ADD CONSTRAINT "chore_rotations_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_rotations" ADD CONSTRAINT "chore_rotations_last_completed_member_id_household_members_id_fk" FOREIGN KEY ("last_completed_member_id") REFERENCES "public"."household_members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_rotations" ADD CONSTRAINT "chore_rotations_chore_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chores"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_rotations" ADD CONSTRAINT "chore_rotations_current_member_fk" FOREIGN KEY ("chore_id","current_member_id") REFERENCES "public"."chore_rotation_members"("chore_id","member_id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
CREATE INDEX "chore_rotation_members_member_id_idx" ON "chore_rotation_members" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "chore_rotation_members_household_id_idx" ON "chore_rotation_members" USING btree ("household_id");--> statement-breakpoint
CREATE INDEX "chore_rotations_household_id_idx" ON "chore_rotations" USING btree ("household_id");--> statement-breakpoint
CREATE POLICY "chore_rotation_members_select" ON "chore_rotation_members" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_rotation_members"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_rotation_members_insert" ON "chore_rotation_members" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_parent("chore_rotation_members"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_rotation_members_update" ON "chore_rotation_members" AS PERMISSIVE FOR UPDATE TO "authenticated_backend" USING (app.is_household_parent("chore_rotation_members"."household_id")) WITH CHECK (app.is_household_parent("chore_rotation_members"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_rotation_members_delete" ON "chore_rotation_members" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_household_parent("chore_rotation_members"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_rotations_select" ON "chore_rotations" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_rotations"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_rotations_insert" ON "chore_rotations" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_parent("chore_rotations"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_rotations_update" ON "chore_rotations" AS PERMISSIVE FOR UPDATE TO "authenticated_backend" USING (app.is_household_parent("chore_rotations"."household_id")) WITH CHECK (app.is_household_parent("chore_rotations"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_rotations_delete" ON "chore_rotations" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_household_parent("chore_rotations"."household_id"));--> statement-breakpoint

-- The default privileges from 0002 already cover these new tables; this keeps
-- the grants explicit (as 0005 and 0006 do). RLS still decides which rows.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE chore_rotations, chore_rotation_members TO authenticated_backend;
