-- SB-26: chore completions and the points ledger, plus a per-member weekly
-- goal. The functions that complete stages and chores, reopen completions,
-- and write the ledger rows are in 0011. See "Completions and points" in
-- ../README.md.
-- Generated by drizzle-kit; hand edits: this header, and the grants at the end.

CREATE TYPE "public"."points_reason" AS ENUM('completion', 'reversal', 'reward_claim', 'adjustment');--> statement-breakpoint
CREATE TABLE "chore_completions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"chore_id" uuid NOT NULL,
	"instance_id" uuid NOT NULL,
	"member_id" uuid,
	"points" integer NOT NULL,
	"completed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reopened_at" timestamp with time zone,
	"reopened_by" uuid
);
--> statement-breakpoint
ALTER TABLE "chore_completions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "points_ledger" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"member_id" uuid NOT NULL,
	"delta" integer NOT NULL,
	"reason" "points_reason" NOT NULL,
	"completion_id" uuid,
	"note" text,
	"created_by" uuid DEFAULT app.current_user_id(),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "points_ledger_delta_check" CHECK ("points_ledger"."delta" <> 0),
	CONSTRAINT "points_ledger_source_check" CHECK ("points_ledger"."reason" in ('completion', 'reversal') or "points_ledger"."completion_id" is null),
	CONSTRAINT "points_ledger_sign_check" CHECK (("points_ledger"."reason" <> 'completion' or "points_ledger"."delta" > 0)
				and ("points_ledger"."reason" not in ('reversal', 'reward_claim') or "points_ledger"."delta" < 0)),
	CONSTRAINT "points_ledger_note_check" CHECK (("points_ledger"."note" is null or char_length("points_ledger"."note") <= 200)
				and ("points_ledger"."reason" <> 'adjustment' or char_length(btrim("points_ledger"."note")) >= 1))
);
--> statement-breakpoint
ALTER TABLE "points_ledger" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "household_members" ADD COLUMN "weekly_goal_points" integer DEFAULT 200 NOT NULL;--> statement-breakpoint
ALTER TABLE "chore_completions" ADD CONSTRAINT "chore_completions_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_completions" ADD CONSTRAINT "chore_completions_member_id_household_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."household_members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_completions" ADD CONSTRAINT "chore_completions_reopened_by_user_id_fk" FOREIGN KEY ("reopened_by") REFERENCES "neon_auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_completions" ADD CONSTRAINT "chore_completions_instance_fk" FOREIGN KEY ("instance_id","chore_id") REFERENCES "public"."chore_instances"("id","chore_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_completions" ADD CONSTRAINT "chore_completions_chore_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chores"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "points_ledger" ADD CONSTRAINT "points_ledger_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "points_ledger" ADD CONSTRAINT "points_ledger_completion_id_chore_completions_id_fk" FOREIGN KEY ("completion_id") REFERENCES "public"."chore_completions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "points_ledger" ADD CONSTRAINT "points_ledger_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "neon_auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "points_ledger" ADD CONSTRAINT "points_ledger_member_fk" FOREIGN KEY ("member_id","household_id") REFERENCES "public"."household_members"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "chore_completions_instance_id_open_key" ON "chore_completions" USING btree ("instance_id") WHERE "chore_completions"."reopened_at" is null;--> statement-breakpoint
CREATE INDEX "chore_completions_household_id_completed_at_idx" ON "chore_completions" USING btree ("household_id","completed_at");--> statement-breakpoint
CREATE INDEX "chore_completions_member_id_completed_at_idx" ON "chore_completions" USING btree ("member_id","completed_at");--> statement-breakpoint
CREATE UNIQUE INDEX "points_ledger_completion_id_completion_key" ON "points_ledger" USING btree ("completion_id") WHERE "points_ledger"."reason" = 'completion';--> statement-breakpoint
CREATE UNIQUE INDEX "points_ledger_completion_id_reversal_key" ON "points_ledger" USING btree ("completion_id") WHERE "points_ledger"."reason" = 'reversal';--> statement-breakpoint
CREATE INDEX "points_ledger_member_id_created_at_idx" ON "points_ledger" USING btree ("member_id","created_at");--> statement-breakpoint
CREATE INDEX "points_ledger_household_id_created_at_idx" ON "points_ledger" USING btree ("household_id","created_at");--> statement-breakpoint
ALTER TABLE "household_members" ADD CONSTRAINT "household_members_weekly_goal_points_check" CHECK ("household_members"."weekly_goal_points" >= 0);--> statement-breakpoint
CREATE POLICY "chore_completions_select" ON "chore_completions" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_completions"."household_id"));--> statement-breakpoint
CREATE POLICY "points_ledger_select" ON "points_ledger" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("points_ledger"."household_id"));--> statement-breakpoint
CREATE POLICY "points_ledger_insert" ON "points_ledger" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_parent("points_ledger"."household_id")
				and "points_ledger"."reason" = 'adjustment'
				and "points_ledger"."created_by" = (select app.current_user_id()));

-- The default privileges from 0002 would give the RLS role full access to
-- these new tables, so narrow them to match the policies. Completions are
-- written only by the SECURITY DEFINER functions in 0011. The ledger is
-- append-only: parents may insert adjustments, and nothing updates or
-- deletes a row.
REVOKE ALL ON TABLE chore_completions, points_ledger FROM authenticated_backend;
--> statement-breakpoint
GRANT SELECT ON TABLE chore_completions TO authenticated_backend;
--> statement-breakpoint
GRANT SELECT, INSERT ON TABLE points_ledger TO authenticated_backend;
--> statement-breakpoint
-- household_members has column-level UPDATE grants (0005); parents set the
-- weekly goal through the existing update policy.
GRANT UPDATE (weekly_goal_points) ON TABLE household_members TO authenticated_backend;
