-- SB-27: the rewards catalog and claims. A claim writes a reward_claims row and a
-- negative reward_claim ledger row in one statement (claimReward() in the web
-- app). See "Rewards" in ../README.md.
-- Generated by drizzle-kit; hand edits: this header, and the grants at the end.

CREATE TYPE "public"."reward_kind" AS ENUM('personal', 'family_milestone');--> statement-breakpoint
CREATE TABLE "reward_claims" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"reward_id" uuid NOT NULL,
	"member_id" uuid NOT NULL,
	"cost_points" integer NOT NULL,
	"single_use" boolean NOT NULL,
	"claimed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reward_claims" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "rewards" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"cost_points" integer NOT NULL,
	"kind" "reward_kind" DEFAULT 'personal' NOT NULL,
	"repeatable" boolean DEFAULT false NOT NULL,
	"created_by" uuid DEFAULT app.current_user_id(),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rewards_id_household_id_key" UNIQUE("id","household_id"),
	CONSTRAINT "rewards_title_check" CHECK (char_length(btrim("rewards"."title")) between 1 and 100),
	CONSTRAINT "rewards_description_check" CHECK ("rewards"."description" is null or char_length("rewards"."description") <= 500),
	CONSTRAINT "rewards_cost_points_check" CHECK ("rewards"."cost_points" between 1 and 100000),
	CONSTRAINT "rewards_milestone_not_repeatable_check" CHECK ("rewards"."kind" = 'personal' or not "rewards"."repeatable")
);
--> statement-breakpoint
ALTER TABLE "rewards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "points_ledger" ADD COLUMN "reward_claim_id" uuid;--> statement-breakpoint
ALTER TABLE "reward_claims" ADD CONSTRAINT "reward_claims_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reward_claims" ADD CONSTRAINT "reward_claims_reward_fk" FOREIGN KEY ("reward_id","household_id") REFERENCES "public"."rewards"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reward_claims" ADD CONSTRAINT "reward_claims_member_fk" FOREIGN KEY ("member_id","household_id") REFERENCES "public"."household_members"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rewards" ADD CONSTRAINT "rewards_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rewards" ADD CONSTRAINT "rewards_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "neon_auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "reward_claims_reward_id_member_id_single_use_key" ON "reward_claims" USING btree ("reward_id","member_id") WHERE "reward_claims"."single_use";--> statement-breakpoint
CREATE INDEX "reward_claims_member_id_claimed_at_idx" ON "reward_claims" USING btree ("member_id","claimed_at");--> statement-breakpoint
CREATE INDEX "reward_claims_household_id_idx" ON "reward_claims" USING btree ("household_id");--> statement-breakpoint
CREATE INDEX "rewards_household_id_idx" ON "rewards" USING btree ("household_id");--> statement-breakpoint
ALTER TABLE "points_ledger" ADD CONSTRAINT "points_ledger_reward_claim_id_reward_claims_id_fk" FOREIGN KEY ("reward_claim_id") REFERENCES "public"."reward_claims"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "points_ledger_reward_claim_id_key" ON "points_ledger" USING btree ("reward_claim_id") WHERE "points_ledger"."reason" = 'reward_claim';--> statement-breakpoint
ALTER TABLE "points_ledger" ADD CONSTRAINT "points_ledger_reward_claim_source_check" CHECK ("points_ledger"."reward_claim_id" is null or "points_ledger"."reason" = 'reward_claim');--> statement-breakpoint
CREATE POLICY "reward_claims_select" ON "reward_claims" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("reward_claims"."household_id"));--> statement-breakpoint
CREATE POLICY "rewards_select" ON "rewards" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("rewards"."household_id"));--> statement-breakpoint
CREATE POLICY "rewards_insert" ON "rewards" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_parent("rewards"."household_id")
				and "rewards"."created_by" = (select app.current_user_id()));--> statement-breakpoint
CREATE POLICY "rewards_update" ON "rewards" AS PERMISSIVE FOR UPDATE TO "authenticated_backend" USING (app.is_household_parent("rewards"."household_id")) WITH CHECK (app.is_household_parent("rewards"."household_id"));--> statement-breakpoint
CREATE POLICY "rewards_delete" ON "rewards" AS PERMISSIVE FOR DELETE TO "authenticated_backend" USING (app.is_household_parent("rewards"."household_id"));

-- Claims are written by claimReward() (as the table owner, like the rest of the
-- web app's writes), never by the RLS role, so it only gets to read them.
REVOKE ALL ON TABLE reward_claims FROM authenticated_backend;
--> statement-breakpoint
GRANT SELECT ON TABLE reward_claims TO authenticated_backend;
