-- SB-28: the time zone a household's days (and streaks) are counted in.
-- Generated by drizzle-kit; hand edits: this header.

ALTER TABLE "households" ADD COLUMN "timezone" text DEFAULT 'UTC' NOT NULL;--> statement-breakpoint
ALTER TABLE "households" ADD CONSTRAINT "households_timezone_check" CHECK (char_length("households"."timezone") between 1 and 64);