-- SB-29: the log behind the Overview "Remind" and "Skip" actions.
-- Generated by drizzle-kit; hand edits: this header and the grants at the end.

CREATE TABLE "chore_reminders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"chore_id" uuid NOT NULL,
	"assignee_member_id" uuid NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"dismissed_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "chore_reminders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "chore_skips" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"chore_id" uuid NOT NULL,
	"period_start" date NOT NULL,
	"member_id" uuid,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chore_skips_chore_period_member_key" UNIQUE("chore_id","period_start","member_id")
);
--> statement-breakpoint
ALTER TABLE "chore_skips" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chore_reminders" ADD CONSTRAINT "chore_reminders_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_reminders" ADD CONSTRAINT "chore_reminders_assignee_member_id_household_members_id_fk" FOREIGN KEY ("assignee_member_id") REFERENCES "public"."household_members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_reminders" ADD CONSTRAINT "chore_reminders_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "neon_auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_reminders" ADD CONSTRAINT "chore_reminders_chore_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chores"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_skips" ADD CONSTRAINT "chore_skips_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_skips" ADD CONSTRAINT "chore_skips_member_id_household_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."household_members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_skips" ADD CONSTRAINT "chore_skips_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "neon_auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore_skips" ADD CONSTRAINT "chore_skips_chore_fk" FOREIGN KEY ("chore_id","household_id") REFERENCES "public"."chores"("id","household_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chore_reminders_assignee_member_id_created_at_idx" ON "chore_reminders" USING btree ("assignee_member_id","created_at");--> statement-breakpoint
CREATE INDEX "chore_reminders_household_id_created_at_idx" ON "chore_reminders" USING btree ("household_id","created_at");--> statement-breakpoint
CREATE INDEX "chore_skips_household_id_created_at_idx" ON "chore_skips" USING btree ("household_id","created_at");--> statement-breakpoint
CREATE POLICY "chore_reminders_select" ON "chore_reminders" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_reminders"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_reminders_insert" ON "chore_reminders" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_parent("chore_reminders"."household_id")
				and ("chore_reminders"."assignee_member_id" is null or app.is_member_id_in("chore_reminders"."household_id", "chore_reminders"."assignee_member_id")));--> statement-breakpoint
CREATE POLICY "chore_reminders_update" ON "chore_reminders" AS PERMISSIVE FOR UPDATE TO "authenticated_backend" USING (app.is_own_member("chore_reminders"."assignee_member_id") or app.is_household_parent("chore_reminders"."household_id")) WITH CHECK (app.is_own_member("chore_reminders"."assignee_member_id") or app.is_household_parent("chore_reminders"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_skips_select" ON "chore_skips" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (app.is_household_member("chore_skips"."household_id"));--> statement-breakpoint
CREATE POLICY "chore_skips_insert" ON "chore_skips" AS PERMISSIVE FOR INSERT TO "authenticated_backend" WITH CHECK (app.is_household_parent("chore_skips"."household_id"));--> statement-breakpoint

-- RLS can't limit columns, so narrow the default privileges from 0002 (full
-- access) to what the policies allow. Both tables are append-only logs: a
-- reminder can only have its `dismissed_at` set, and a skip is never changed.
REVOKE ALL ON TABLE chore_reminders FROM authenticated_backend;
--> statement-breakpoint
GRANT SELECT, INSERT ON TABLE chore_reminders TO authenticated_backend;
--> statement-breakpoint
GRANT UPDATE (dismissed_at) ON TABLE chore_reminders TO authenticated_backend;
--> statement-breakpoint
REVOKE ALL ON TABLE chore_skips FROM authenticated_backend;
--> statement-breakpoint
GRANT SELECT, INSERT ON TABLE chore_skips TO authenticated_backend;
